name: bitcoin_preco
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0-250.0.dev <3.0.0'

dependencies:
  
  brasil_fields: ^1.4.5
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  #flutter_launcher_icons: ^0.9.2
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
 
  image_path: "dev_assets/bitcoin.png"
  adaptative_icon_background: "#FFC107"
  adaptative_icon_foreground: "dev_assets/bitcoin.png"

flutter: 
  uses-material-design: true

  assets:
    - imagens/logobtc.png
    - imagens/Screenshot_1656935571.png

